### ISSUE TITLE
Minecraft Crashed

### ISSUE THREAD

**Issue by 007lol** [LogicTechCorp/NetherEx-Archive#224]
Potential Causes is this Mod
heres the link:
https://paste.dimdev.org/usucidotik.mccrash

**Comment by LogicTechCorp** [comment]
This issue is caused because NEX couldn't read the pigtificate config files. Try deleting the folder at "world_name_here\config\netherex\pigtificate_trades". If the issue still occurs then it might be caused by another mod or program preventing me from accessing the config files. I am implementing a fix that will stop the game from crashing from this issue in the next release.
