### ISSUE TITLE
Pigtificate Generation in 1.12.2

### ISSUE THREAD

**Issue by UnpeelableBanana** [LogicTechCorp/NetherEx-Archive#230]
Hello,
This is one of my favorite mods but I am having problems locating pigtificate villages. I have better nether and primal core as other mods which generate things on the floor of the nether. I was wondering if these mods are causing the issue or there is something I can do related to the config. 

I have spent multiple hours looking for the pigtificate villages yet I have not located one of them. Please let me know if this issue has been fixed or if there is an easy fix to this issue.

**Comment by LogicTechCorp** [comment]
The pigtificate villages need a large open area of netherrack to generate on. So, the other mods are interfering with the generation because they are generating things on top of the Netherrack. There's not much you can do besides removing the other mods or reducing their generation if the have config options for it.
