### ISSUE TITLE
[Enhancement] Adding ability to disable certain mobs or change spawnrates

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [LogicTechCorp/NetherEx-Archive#238]
The mod changes wither skeletons to spawn everywhere instead of in nether forts and it causes them to spawn way too frequently. 

Could you please add a way to change spawn rates of individual mobs (from 0% chance to X% chance).

Very neat plugin, would be more usable with this feature though.

**Comment by LogicTechCorp** [comment]
NetherEx only causes wither skeletons to spawn in the Ruthless Sands biome. If they are spawning elsewhere, it is caused by another mod. You can customize spawn rates if you go to "minecraft_install_location/saves/world_name_here/config/netherex/nether_biomes/netherex/ruthless_sands.json". Here is what the default is:
```
{
	"spawnWeight": 65,
	"minimumGroupCount": 1,
	"maximumGroupCount": 4,
	"entity": "minecraft:wither_skeleton"
}
```
You can set "spawnWeight" to 0 to disable spawning. A lower spawnWeight means less will spawn compared to other mobs while a higher spawnWeight means more will spawn compared to other mobs. You can also adjust the amount that spawn together by adjusting the minimum and maximum group counts.
