### ISSUE TITLE
NetherEx combined with Extended Nether causes a crash on start-up

### ISSUE THREAD

**Issue by mosharky** [LogicTechCorp/NetherEx-Archive#255]
[Crash report](https://pastebin.com/psLV7Ce9) as well as the [latest.log](https://pastebin.com/rsZjmEZB)

here's extended nether: https://www.curseforge.com/minecraft/mc-mods/extended-nether

**Comment by ItsBlackGear** [comment]
hello, there's no need to create a report for this issue because is an extended nether side crash and it's already solved in the upcoming version of the mod, it's said on the extended nether discord that the mod doesn't have compatibilities with byg (multiplayer) and netheex on 2.0 and 3.0 versions, 4.0 already have them, just need to be a bit patient
