### ISSUE TITLE
[1.12.2] 2.2.0 new config

### ISSUE THREAD

**Issue by Sereath** [LogicTechCorp/NetherEx-Archive#262]
We tried using the new  **# Use global biome configs** so we could stop using the copypaste mod for our modpack and easily apply our own configs for every new world, but it doesnt seem to be working at all.

What we first did:

-Updated NetherEx to 2.2.0 from 2.1.8 and its library
-Deleted the old config folder
-Launched the game once so we could generate a new config folder, closed it after.

-Changed
**B:useGlobalBiomeConfigs=true** 
**B:usePerWorldBiomeConfigs=false** 

-Launched the game once again so it could generate two new folders inside **netherex**: **nether_biomes** and **pigtificate_trades**.
-Closed the game.
-Tweaked the newly generated jsons that came inside **nether_biomes** to our liking.
-Opened the game.
-Generated a new world.

And the nether was still being generated with the default biome weights that come with the default settings inside the **nether_biomes** folder and same thing with the mobs spawns.

![image](https://user-images.githubusercontent.com/54506307/100694980-d98c0100-3355-11eb-9375-a2fb9da6e92f.png)
The mobs shown above are actually the very same ones that we had removed from the default biome jsons along with other weird default spawns like having endermen spawn everywhere, including some mobs from 3 other different mods. Same thing with the biomes distribution, some of the ones that we had set to 1 and 0 are being generated as high as the default jsons.

After acknowledging this with simply decided to use the Copy-Paste mod once again since we already had a working setup before updating, so we just changed these back:
**B:useGlobalBiomeConfigs=false** 
**B:usePerWorldBiomeConfigs=true** 

We go try a new world but the issue persists. So what we noticed after looking inside the world's newly generated own config is that netherex was directly overwriting our custom jsons copied there by copypaste. 
We also tried setting both of those settings to true and nothing changed.

So no matter what we did, NetherEx would still use the default settings. We have not done anything with _pigtificate trades_ yet so we can't speak for those.

Other only biome mod we have for the nether is Biomes O' Plenty.

**Comment by LogicTechCorp** [comment]
I followed the provided steps on a single player world and on a server world, but I wasn't able to reproduce this issue. Which forge version was used and what other mods were installed? Were any of the biome configs deleted? When a mob spawn is removed from a biome config, the handling of the spawn reverts back to whichever mod the mob is from.

**Comment by Sereath** [comment]
Forge 14.23.5.**2847**

The spawns weren't an issue in the previous version, neither were the biome weights. We deleted, regenerated and tweaked the configs several times just to be sure.
Yes we have over 200+ mods already in this pack however we cant afford moving out any of them so I understand if nothing can really be done, never saw any errors on the console either. We could always just downgrade the NetherEx version, so just a heads up if anyone ever experiences something like this.

Edit: Here is the list, just in case. No other biome mod was updated at this time.
[modlist.txt](https://github.com/LogicTechCorp/NetherEx/files/5621860/modlist.txt)

**Comment by Sereath** [comment]
I sincerely cant understand what happened. 

Today I just cloned the instance I work in for our modpack. This was done in MultiMC.
Then I downgraded 1 version to see if our copypaste method still worked, it did. 
Ok good
Then just out of curiosity I updated once again to the newest version, did not even get to redownload from Curseforge, I just took the file back from the recycle bin. To see if our copypaste method still worked with the newest version which is **2.2.0** and it did. I really don't know why it wasn't working yesterday.

Ok so now I go and try the original plan again, which is to get rid of the copypaste mod so we can simply use the new global configs option.

**B:useGlobalBiomeConfigs=true
B:usePerWorldBiomeConfigs=false**

(I'm back on the original instance, have not changed anything in there.)

And it just works. The biomes are using the corrects weights now. Flew around for several minutes just to make sure, yesterday I did the same thing.
![image](https://user-images.githubusercontent.com/54506307/100804709-f591b000-33f2-11eb-8f2b-80726f018e14.png)
The original intend was to mostly only have the Artic Abyss and Ruthless Sands generate along with the default Hell biome. It is now working. 
Yesterday I Should have included a pic of the Nether when it was generating the biomes with the default weights, some of them were supposed to be at 0 but were somehow still being generated very often.

So my apologies, I sincerely cant understand what went wrong yesterday
and thank you very much for this last update.

**Comment by TheTennessee** [comment]
Uh, this is not just happening to one person. I was having this same issue, where suddenly as I was loading new chunks of the nether, they were generating oddly, using blocks I had told it to stop using (I had transformed the torrid wasteland into a 1.16 style basalt delta with blocks from another mod, and suddenly that biome was generating closer to what it originally was in netherex). Also, all of my biomes from biomes o plenty were generating without a layer of bedrock on the roof, but ONLY the biomes o plenty biomes. Hell and the netherex biomes were working fine.
If I turn off "B:overrideNether", I get back the bedrock on the roof, but now Torrid Wasteland won't spawn. I have not yet gotten mine to go back to normal. My config is set the same way as his, set to take the global config, not per world. I didn't have this issue prior to 2.2.0. I had been using nether ex with BoP just fine before. I have updated to the 2.2.1 version, with no change.

**Comment by LogicTechCorp** [comment]
I'll take another look into this issue and I'll look into the bedrock issue.

**Comment by LogicTechCorp** [comment]
I did some more testing and I still couldn't reproduce the issue. However, I did make some changes to how I handle the biome configs and I fixed some other issues I found with them. Try the latest version to see if any of the changes I made fix the issue. I also fixed the Bedrock layers missing from the Biomes O' Plenty biomes.

**Comment by TheTennessee** [comment]
Big thumbs up on fixing the bedrock layer, that seems to have worked like a charm! However, the issue I am having with the configs doesn't seem resolved. I can give some extra information here to hopefully solve it. I am using the biome Torrid Wasteland as a way to recreate the basalt deltas from 1.16. I have a mod called Netherbackport which adds the blocks in, but it doesn't create the biomes. So along with your mod, and COFH world, I do some custom world generation to recreate it.
Now, in the latest version, when Torrid Wasteland is generated, it looks MOSTLY right, except for one block. It creates the basalt, and all of COFH world's generation happens, but the fill block was set to Netherrack (with fiery netherrack only generating down at lava lake level through COFH world, because I like the blocks you added, I just wanted them to be a tad more rare rather than replacing the netherrack entirely). Here is my Torrid Wasteland config:
`{
	"biome": "netherex:torrid_wasteland",
	"generationWeight": 5,
	"useDefaultDecorations": true,
	"isSubBiome": false,
	"isEnabled": true,
	"blocks": {
		"caveFloorBlock": {
			"block": "netherbackport:basalt"
		},
		"fluidBlock": {
			"block": "minecraft:lava"
		},
		"caveWallBlock": {
			"block": "netherbackport:basalt"
		},
		"surfaceBlock": {
			"block": "netherbackport:basalt"
		},
		"subsurfaceBlock": {
			"block": "minecraft:netherrack"
		},
		"caveCeilingBlock": {
			"block": "netherbackport:basalt"
		}
	},
[...]
`
As you can see, the subsurface block is supposed to be netherrack, but when I go into the world, it is still fiery netherrack.

![2020-12-13_13 57 09](https://user-images.githubusercontent.com/5052078/102021146-c6146900-3d4b-11eb-8cd3-a85867536fcb.png)

So, since the bedrock is fixed, and I am fairly skilled with COFH world, I am for the time being, going to tell COFH world to manually replace the fiery netherrack, and keep using the latest version. I don't think I care enough about it to not use the latest version of the mod (which I really wanted to update for pigtificate curing). I still give this a big two thumbs up since it fixed the nether roof, and I'll follow the mod whenever you send out the next update and see if it fixed the configs fully.

**Comment by LogicTechCorp** [comment]
Can you try loading up a new world with only LibraryEx, NetherEx, and Nether Backport installed, editing the Torrid Wasteland config, and checking if the issue still occurs? Also, is your Torrid Wasteland config from an earlier version of NetherEx? I am asking because it has the "caveCeilingBlock", "caveFloorBlock", and "caveWallBlock" values which were removed.
