### ISSUE TITLE
non-Nether mobs

### ISSUE THREAD

**Issue by icespike03** [LogicTechCorp/NetherEx-Archive#270]
i found these mobs that shouldn't be in nether, mod versions are: LibraryEX 1.2.1 and NetherEX 2.2.2. the mods of the mobs are: Grimoire of Gaia and Primitive mobs
![2021-02-22_21 36 44](https://user-images.githubusercontent.com/71431866/108771674-492c1980-755c-11eb-9c93-1304b985aa7a.png)
![2021-02-22_21 37 08](https://user-images.githubusercontent.com/71431866/108771722-577a3580-755c-11eb-870d-d536f51024a2.png)
![2021-02-22_21 41 59](https://user-images.githubusercontent.com/71431866/108771745-5c3ee980-755c-11eb-9d49-2a6bf548880a.png)
![2021-02-22_21 35 32](https://user-images.githubusercontent.com/71431866/108771796-6b259c00-755c-11eb-9960-4a5a704df6a0.png)
![2021-02-22_21 36 14](https://user-images.githubusercontent.com/71431866/108771801-6cef5f80-755c-11eb-9ebf-732c0dafbebc.png)
![2021-02-22_21 36 19](https://user-images.githubusercontent.com/71431866/108771824-737dd700-755c-11eb-94c4-e2536fc804b3.png)

**Comment by LogicTechCorp** [comment]
What are the names of each mob?

**Comment by Sereath** [comment]
Ive experienced the very same problem.
Mobs are as follow for each picture posted above: 

grimoireofgaia:mummy

grimoireofgaia:creep

primitivemobs:festive_creeper // (However this one might be intentional from the dev)

grimoireofgaia:goblin_feral

grimoireofgaia:ender_eye

Same thing happens with some of _Fish's Undead Rising_ mobs and _Better Animals Plus_ tarantulas.

**Comment by LogicTechCorp** [comment]
This issue is caused by the other mods incorrectly adding their mob spawns to biomes which are tagged as Nether.
